# ***Linear Algebra***

### Matrix Operation 

In this part of the program,We will be using numpy (Numerical Python) library which is used for numerical computations.It supports for  multi-dimensional arrays (matrices) and mathematical operations on them.

Q.Perform the following operations on the given matrices:
A=[[2    -1], [​0    3​]]
B=[[1   ​ 2], [-3      4​]]
a. A+B
b. AB
c. 3A−2B

In [1]:
import numpy as np

In [2]:


A = np.array([
    [2, -1],
    [0, 3],
])

B = np.array([
    [1, 2],
    [-3, 4],
])

print(A + B)
print()
print(A * B)      # element-wise multiplication
print()
print(3*A - 2*B)


[[ 3  1]
 [-3  7]]

[[ 2 -2]
 [ 0 12]]

[[ 4 -7]
 [ 6  1]]


## Determinants and Inverses  
Q.Find the determinant of A.
Determine whether A is invertible. If yes, calculate A−1.

In [3]:
import numpy.linalg as LA
LA.det(A)

np.float64(6.0)

Here we have imported <u>numpy.linalg</u> which is sub module of numpy for linear algebra operations in our programs to find determinant, inverse, rank, eigenvalues, and solving linear equations.LA.det(A) is used to calculate the determinant of a matrix. <u>LA.det(A)</u> which is important because:

Checks if a matrix is invertible

If det(A) ≠ 0 → inverse exists

If det(A) = 0 → inverse does not exist

## Eigen Values and Eigen Vectors:
Eigenvalues and Eigenvectors are fundamental concepts in linear algebra and play a major role in data science, especially in dimensionality reduction, feature extraction, and data transformation. It is important for PCA(Principal Component Analysis) where data varies the most. Eigenvectors show where the data is pointing,
Eigenvalues show how important that direction is. It is also used in preprocessing before ML model.



Q.Compute the eigenvalues and eigenvectors of the matrix:
C=[[4    1], [​−2       1]​]


In [4]:
C = np.array([[4, 1],
              [-2, 1]])

eigenvalues, eigenvectors = np.linalg.eig(C)

print("Matrix A:")
print(C)
print("\nEigenvalue (first):")
print(eigenvalues[0])
print("\nCorresponding Eigenvector:")
print(eigenvectors[:, 0])

Matrix A:
[[ 4  1]
 [-2  1]]

Eigenvalue (first):
3.0

Corresponding Eigenvector:
[ 0.70710678 -0.70710678]


## Car Price Prediction using Linear Regression

You are given a dataset of cars with the following features:Number of cylinders (x1​), Engine size in liters (x2​), Horsepower (x3)

car 1:

x1: 4

x2:  1.5

x3: 100

and price: 20


car 2:

x1: 6

x2:  2.0

x3: 150

and price: 30

Then, find the price of a car 3 with features

x1: 8

x2:  3.0

x3: 200

price:?



In [5]:
# Feature matrix (2 cars, 3 features)
# x1 = cylinders, x2 = engine size, x3 = horsepower
X = np.array([
    [4, 1.5, 100],   # Car 1
    [6, 2.0, 150]    # Car 2
])

# Price vector
y = np.array([20, 30])
XXT=X @ X.T
print("\nX X^T:\n",XXT)

XXT_invert=LA.inv(XXT)
print("\n(X*X^T)^-1\n",XXT_invert)

beta=X.T @ XXT_invert @ y
print("\nRegression Coefficient(beta):\n",beta)

car3_features = np.array([8, 3.0, 200])
car3_price = car3_features @ beta
print(f"\nPredicted price for Car 3: {car3_price:.2f}")



X X^T:
 [[10018.25 15027.  ]
 [15027.   22540.  ]]

(X*X^T)^-1
 [[ 36.00638978 -24.00479233]
 [-24.00479233  16.00359425]]

Regression Coefficient(beta):
 [7.98722045e-03 1.42108547e-13 1.99680511e-01]

Predicted price for Car 3: 40.00


<p>In this topic, We constructed feature Matrix "X" and Price Vector "y".I used pesudo-inverse because this gives the minimum-norm solution:β vector with smallest magnitude that fits the data.</p>
The pseudo-inverse (also called Moore-Penrose inverse) is a generalization of the matrix inverse for non-square or singular matrices Computed regression coefficient (Beta) and predicted the price of new car usin dot product.

<b>Result: 

Predicted Price of Car3: </b>=40


### Conclusion:
This repository demonstrates the applications of linear algebra and matrix operations in solving real life and data analysis problems.

1.Matrix Operations:
Simple Matrix Addition,Multiplication and scalar operations were performed.It shows the foundation of linear algebra and how it is used to solve real life problems and how datas are processed.

2.Determinant and Inverse:
We calculated the determinant and inverse of given matrix as it was non zero which tell it is invertible.Determinants help check matrix properties (like invertibility), and inverses are essential for solving linear systems and linear regression problems.

3.Eigen_Values and Eigen_Vectors:
We computed the Eigen values and Eigen vectors of the given matrix.
It shows its impact in doing Principal Component Analysis(PCA). They are important in analyzing matrix transformations,stability of systems, and dimensionality reduction techniques in machine learning.

4.Car Price Prediciton(Linear Reression):
We use the pseudo-inverse method to compute regression coefficients from given car feature and price of the given car to predict the of new car. It demonstrated how we can use regression to predict something from given values.
